/* 
  AUTOGENERATED FILE
  Do not manually edit
  Run "npm run generateARMClients" to regenerate
*/

import * as Types from "./types"


        /* Lists all of the available Cosmos DB Resource Provider operations. */
        export async function list (
          
          
        ) : Promise<Types.OperationListResult> {
          return window.fetch(`https://management.azure.com/providers/Microsoft.DocumentDB/operations`, { method: "get",  }).then((response) => response.json())
        }
      