export const requestTimeoutMs = 60000;
export const portalCacheTimeoutMs = 10000;
export const errorNotificationTimeoutMs = 5000;
export const copyHelperTimeoutMs = 2000;
export const waitForDOMElementMs = 500;
export const cacheBustingTimeoutMs = 10 /** minutes **/ * 60 /** to seconds **/ * 1000; /** to milliseconds **/
export const databaseThroughputIncreaseFactor = 100;
export const arcadiaTokenRefreshInterval = 20 /** minutes **/ * 60 /** to seconds **/ * 1000; /** to milliseconds **/
export const arcadiaTokenRefreshIntervalPaddingMs = 2000;
