# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    name: "Unit Tests"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run test --if-present
      - run: npm test
  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build:ci --if-present
  endtoend:
    name: "End to End Tests"
    runs-on: windows-latest
    steps:
      - uses: southpolesteve/cosmos-emulator-github-action@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm start &
        env:
          EMULATOR_ENDPOINT: https://0.0.0.0:8081/
          NODE_TLS_REJECT_UNAUTHORIZED: 0
      - run: npm ci --prefix ./cypress
      - run: npm run test:ci --prefix ./cypress -- --spec ./integration/dataexplorer/ci-tests/createDatabase.spec.ts
        env:
          EMULATOR_ENDPOINT: https://0.0.0.0:8081/
          NODE_TLS_REJECT_UNAUTHORIZED: 0
