# This is a basic workflow to help you get started with Actions

name: Cleanup End to End Account Resources

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # Once every day at 7 AM PST
    - cron: "0 13 * * *"

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cleanupaccounts:
    name: "Cleanup Test Database Accounts"
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.E2ETESTS_SUBSCRIPTION_ID }}
      E2ETESTS_RESOURCEGROUP_NAME : ${{ secrets.E2ETESTS_RESOURCEGROUP_NAME }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: "Az CLI login"
        uses: azure/login@7184910d9eb2b1c5e48f7073824a90609bb9b6d6 # v2.3.1
        with:
          client-id: ${{ secrets.E2ETESTS_CLIENT_ID }}
          tenant-id: ${{ secrets.E2ETESTS_TENANT_ID }}
          subscription-id: ${{ secrets.E2ETESTS_SUBSCRIPTION_ID }}

      - name: Use Node.js 22.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
      - run: npm ci
      - run: node utils/cleanupDBs.js