# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Runners
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  e2erunner:
    runs-on: ubuntu-latest
    name: "End to End Portal Tests"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run test:e2e
        env:
          PORTAL_RUNNER_APP_INSIGHTS_KEY: ${{ secrets.PORTAL_RUNNER_APP_INSIGHTS_KEY }}
          PORTAL_RUNNER_USERNAME: ${{ secrets.PORTAL_RUNNER_USERNAME }}
          PORTAL_RUNNER_PASSWORD: ${{ secrets.PORTAL_RUNNER_PASSWORD }}
          PORTAL_RUNNER_SUBSCRIPTION: 69e02f2d-f059-4409-9eac-97e8a276ae2c
          PORTAL_RUNNER_RESOURCE_GROUP: runners
          PORTAL_RUNNER_DATABASE_ACCOUNT: portal-sql-runner
